# Generated by Django 2.1.2 on 2018-11-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='Profession',
        ),
    ]
