# Generated by Django 2.1.2 on 2018-11-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181102_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Profession',
            new_name='Branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
